<?php
/**
 * @var \Paypal\BraintreeBrasil\Block\Sales\Order\Creditmemo\InstallmentsInterestRate $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $_source = $block->getSource() ?>

<?php if ($_source) : ?>
    <tr>
        <td class="label">
            <?= $escaper->escapeHtml($block->getInstallmentsInterestRateLabel()) ?>
            <div id="installments_interest_rate_adv"></div>
        </td>
        <td>
            <input type="text"
                   name="creditmemo[installments_interest_rate]"
                   value="<?= $block->formatValue($block->getInstallmentsInterestRateAmount()) ?>"
                   class="input-text admin__control-text not-negative-amount"
                   id="installments_interest_rate" />
        </td>
    </tr>
<?php endif; ?>
