<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Paypal\BraintreeBrasil\Block\Info\ApplePay $block */ ?>
<?php $additionalInformation = $block->getInfo()->getAdditionalInformation(); ?>
<p><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?></p>


<table class="admin__table-secondary order-information-table">
    <tr>
        <th class="label">
            <?php echo __('Braintree Transaction ID') ?>
        </th>
        <td class="value">
            <?= $escaper->escapeHtml($block->getTransactionId()) ?>
        </td>
    </tr>
</table>
